src/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('practicas.urls')),
]

src/practicas/urls.py
from django.conf.urls import url
from django.urls import path
from .views import (CreateSolicitud, Solicitudes, ApproveSolicitud, 
                    SolicitudView, RejectSolicitud, DeleteSolicitud,
                    SolicitudDetails, Main, SolicitudCorrection)

urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('crear_solicitud/', CreateSolicitud.as_view(), name='crear_error'),
    path('solicitud/', SolicitudView.as_view(), name='solicitud_error'),
    path('solicitudes/', Solicitudes.as_view(), name='solicitudes_error'),
    path('solicitudes/<str:TOKEN>/', Solicitudes.as_view(), name='solicitudes'),
    path('solicitudes/aprobar/<int:ID>/<str:TOKEN>/', ApproveSolicitud.as_view(), name='approve_solicitud'),
    path('solicitudes/rechazar/<int:ID>/<str:TOKEN>/', RejectSolicitud.as_view(), name='reject_solicitud'),
    path('solicitudes/detalles/<int:ID>/<str:TOKEN>/', SolicitudDetails.as_view(), name='solicitud_details'),
    path('crear_solicitud/<str:TOKEN>/', CreateSolicitud.as_view(), name='create_solicitud'),
    path('solicitud/<str:TOKEN>/', SolicitudView.as_view(), name='solicitud_view'),
    path('solicitud/eliminar/<str:TOKEN>/', DeleteSolicitud.as_view(), name='delete_solicitud'),
    path('solicitud/recorregir/<str:TOKEN>/', SolicitudCorrection.as_view(), name='solicitud_correction'),
    ]

src/practicas/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField

class Solicitud(models.Model):

    rut = models.CharField(verbose_name="rut", max_length=10, unique=True)
    email = models.EmailField(_('email'))
    nombre = models.CharField(verbose_name="nombre", max_length=50)
    carrera = models.CharField(verbose_name="carrera", max_length=60)
    malla = models.CharField(verbose_name="malla", max_length=60, null=True, blank=True)
    started_year = models.IntegerField(verbose_name="started_year")
    telefono = models.IntegerField(verbose_name="telefono")
    celular = models.IntegerField(verbose_name="celular")
    NUMERO_PRACTICA = (
        ('Practica I', 'Practica I'),
        ('Practica II', 'Practica II'),
    )
    numero_practica = models.CharField(max_length=30, choices=NUMERO_PRACTICA,
                                    verbose_name="numero practica")
    nombre_empresa = models.CharField(verbose_name="nombre empresa", max_length=50)
    rubro_empresa = models.CharField(verbose_name="rubro", max_length=30)
    direccion_empresa = models.CharField(verbose_name="direccion", max_length=50)
    website_empresa = models.CharField(verbose_name="website", max_length=30)
    ciudad_empresa = models.CharField(verbose_name="ciudad", max_length=30)
    region_empresa = models.CharField(verbose_name="region", max_length=30)
    pais = CountryField()
    contacto = models.CharField(verbose_name="contacto", max_length=30)
    cargo_contacto = models.CharField(verbose_name="cargo contacto", max_length=30)
    email_contacto = models.EmailField(_('email contacto'))
    telefono_contacto = models.IntegerField(verbose_name="telefono contacto")
    fax_contacto = models.CharField(verbose_name="fax", max_length=30, null=True, blank=True)
    trabaja_empresa = models.BooleanField(verbose_name="trabaja aqui",
                                 default=False, null=True)
    empleados_empresa = models.IntegerField(verbose_name="total empleados empresa")
    empleados_IT = models.IntegerField(verbose_name="total empleados IT")
    descripcion = models.TextField(verbose_name="descripcion empresa", blank=True,
                                   null=True)
    inicio_practica = models.DateField(verbose_name="inicio practica",
                                     max_length=100)
    termino_practica = models.DateField(verbose_name="termino practica",
                                     max_length=100)
    horas_diarias = models.CharField(verbose_name="horas_diarias", max_length=10)
    dias_trabajo = models.CharField(verbose_name="dias trabajo", max_length=100)
    objetivos_generales = models.TextField(verbose_name="objetivos generales")
    actividades_realizar = models.TextField(verbose_name="actividades a realizar")
    status_x = models.BooleanField(default=False, null=True)
    status_m = models.BooleanField(default=False, null=True)
    status_v = models.BooleanField(default=False, null=True)
    is_rejected = models.BooleanField(default=False, null=True, blank=True)
    rejected_reason = models.TextField(verbose_name="razon de rechazo", blank=True,
                                   null=True)

    def __str__(self):
        return self.nombre

src/practicas/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import UpdateView, CreateView
from django.views import View
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib import messages
import sdk as ensena
import requests
from django.core import serializers
import json
from django.conf import settings
from .models import Solicitud
from .forms import CrearSolicitudForm
from .utils import Malla, CheckEIT, CheckVL
from django.shortcuts import get_object_or_404


ensena.SetApp(settings.ENSENA_KEY)

class Main(View):
    template_name = "create_solicitud.html"

    def get(self, request):
        token = request.GET['TOKEN']
        email = ensena.GetUser(token)['User']['Email']
        if CheckEIT(email) or CheckVL(email):
            return redirect('solicitudes', TOKEN=token)
        else:
            return redirect('create_solicitud', TOKEN=token)


class CreateSolicitud(View):
    template_name = "create_solicitud.html"

    def get(self, request, *args, **kwargs):
        try:
            token = kwargs['TOKEN']
        except:
            context = {"error": True}
            return render(request, self.template_name, context)
        try:
            user = ensena.GetUser(token)
        except:
            context = {"error": True}
            return render(request, self.template_name, context)

        if Solicitud.objects.filter(email=user['User']['Email']).exists():
            return redirect('solicitud_view', TOKEN=token)
        form = CrearSolicitudForm(request.GET)
        context = {"form": form, "user": user, "TOKEN": token}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        try:
            token = kwargs['TOKEN']
        except:
            context = {"error": True}
            return render(request, self.template_name, context)
        try:
            user = ensena.GetUser(token)
        except:
            context = {"error": True}
            return render(request, self.template_name, context)
        form = CrearSolicitudForm(request.POST)
        days = form['dias_trabajo'].value()
        if form.is_valid():
            solicitud = Solicitud(**form.cleaned_data)
            if solicitud.numero_practica == 'Practica I':
                solicitud.malla = Malla(user['User']['CoursesApproved'], user['User']['Courses'], 1)
            elif solicitud.numero_practica == 'Practica II':
                solicitud.malla = Malla(user['User']['CoursesApproved'], user['User']['Courses'], 2)
            solicitud.save()
        else:
            context = {'errors': form.errors.values , 'form': form, 'user': user, 'TOKEN': token,
                       'days': days}
            return render(request, self.template_name, context)
        return redirect('create_solicitud', TOKEN=token)


class Solicitudes(View):
    template_name = "solicitudes.html"

    def get(self, request, *args, **kwargs):
        try:
            token = kwargs['TOKEN']
        except:
            context = {"error": True}
            return render(request, self.template_name, context)
        try:
            email = ensena.GetUser(token)['User']['Email']
        except:
            context = {"error": True}
            return render(request, self.template_name, context)

        if CheckEIT(email):
            queryset = Solicitud.objects.filter(status_m=False, is_rejected=False)

        elif CheckVL(email):
            queryset = Solicitud.objects.filter(status_v=False, is_rejected=False)
        else:
            context = {"error": True}
            return render(request, self.template_name, context)
        context = {"solicitudes": queryset, "TOKEN": token}
        return render(request, self.template_name, context)


class ApproveSolicitud(View):
    template_name = 'approve_solicitud.html'

    def get(self, request, *args, **kwargs):
        pk = kwargs['ID']
        try:
            token = kwargs['TOKEN']
        except:
            return redirect('solicitudes_error')
        solicitud = get_object_or_404(Solicitud, pk=pk)
        context = {"solicitud": solicitud, "TOKEN": token}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        pk = kwargs['ID']
        try:
            token = kwargs['TOKEN']
        except:
            return redirect('solicitudes_error')
        try:
            email = ensena.GetUser(token)['User']['Email']
        except:
            return redirect('solicitudes', TOKEN=token)
        solicitud = get_object_or_404(Solicitud, pk=pk)
        if CheckEIT(email):
            solicitud.status_m = True
            solicitud.save()
            messages.success(request, "Solicitud aprobada correctamente")
            return redirect('solicitudes', TOKEN=token)

        elif CheckVL(email):
            solicitud.status_v = True
            solicitud.save()
            messages.success(request, "Solicitud aprobada correctamente")
            return redirect('solicitudes', TOKEN=token)

        else:
            return redirect('solicitudes', TOKEN=token)


class SolicitudView(View):
    template_name = "solicitud_view.html"

    def get(self, request, *args, **kwargs):
        try:
            token = kwargs['TOKEN']
        except:
            context = {"error": True}
            return render(request, self.template_name, context)
        try:
            user = ensena.GetUser(token)
        except:
            context = {"error": True}
            return render(request, self.template_name, context)
        if Solicitud.objects.filter(email=user['User']['Email']).exists():
            solicitud = Solicitud.objects.get(email=user['User']['Email'])
            context = {"solicitud": solicitud, "TOKEN": token}
            return render(request, self.template_name, context)
        else:
            return redirect('create_solicitud', TOKEN=token)


class RejectSolicitud(View):
    template_name = "reject_solicitud.html"

    def get(self, request, *args, **kwargs):
        pk = kwargs['ID']
        try:
            token = kwargs['TOKEN']
        except:
            return redirect('solicitudes_error')
        try:
            user = ensena.GetUser(token)
        except:
            return redirect('solicitudes', TOKEN=token)
        solicitud = get_object_or_404(Solicitud, pk=pk)
        context = {"solicitud": solicitud, "TOKEN": token}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        pk = kwargs['ID']
        try:
            token = kwargs['TOKEN']
        except:
            return redirect('solicitudes_error')
        try:
            email = ensena.GetUser(token)['User']['Email']
        except:
            return redirect('solicitudes', TOKEN=token)
        solicitud = get_object_or_404(Solicitud, pk=pk)

        if CheckEIT(email) or CheckVL(email):
            solicitud.rejected_reason = request.POST['rejected_reason']
            solicitud.status_v = False
            solicitud.status_m = False
            solicitud.is_rejected = True
            solicitud.save()
            messages.success(request, "Solicitud rechazada correctamente")
            return redirect('solicitudes', TOKEN=token)
        else:
            return redirect('solicitudes', TOKEN=token)


class SolicitudDetails(View):
    template_name = "solicitud_details.html"

    def get(self, request, *args, **kwargs):
        pk = kwargs['ID']
        try:
            token = kwargs['TOKEN']
        except:
            return redirect('solicitudes_error')
        try:
            user = ensena.GetUser(token)
        except:
            return redirect('solicitudes', TOKEN=token)

        solicitud = get_object_or_404(Solicitud, pk=pk)
        context = {"solicitud": solicitud, "TOKEN": token}
        return render(request, self.template_name, context)


class DeleteSolicitud(View):
    template_name = "delete_solicitud.html"

    def get(self, request, *args, **kwargs):
        try:
            token = kwargs['TOKEN']
        except:
            return redirect('solicitud_error')
        try:
            user = ensena.GetUser(token)
        except:
            return redirect('solicitud_error', TOKEN=token)
        context = {"TOKEN": token}
        return render(request, self.template_name, context)


    def post(self, request, *args, **kwargs):
        try:
            token = kwargs['TOKEN']
        except:
            return redirect('solicitud_error')
        try:
            email = ensena.GetUser(token)['User']['Email']
        except:
            return redirect('solicitud_error', TOKEN=token)
        solicitud = get_object_or_404(Solicitud, email=email)
        solicitud.delete()
        return redirect('create_solicitud', TOKEN=token)


class SolicitudCorrection(View):
    template_name = "solicitud_correction.html"

    def get(self, request, *args, **kwargs):
        try:
            token = kwargs['TOKEN']
        except:
            return redirect('solicitud_error')
        try:
            email = ensena.GetUser(token)['User']['Email']
        except:
            return redirect('solicitud_error', TOKEN=token)
        solicitud = get_object_or_404(Solicitud, email=email)
        days = solicitud.dias_trabajo.split(", ")
        print(days)
        if solicitud.is_rejected:
            form = CrearSolicitudForm(instance=solicitud)
            context = {"form": form, "TOKEN": token, "days": days}
            return render(request, self.template_name, context)
        else:
            return redirect('solicitud_view', TOKEN=token)


    def post(self, request, *args, **kwargs):
        try:
            token = kwargs['TOKEN']
        except:
            return redirect('solicitud_error')
        try:
            user = ensena.GetUser(token)['User']
        except:
            return redirect('solicitud_error', TOKEN=token)

src/practicas/templates/approve_solicitud.html
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header grey lighten-2">
      <h4 class="modal-title w-100 text-center" id="myModalLabel" style="font-weight: 500;font-size: 1.5rem;">Advertencia Aprobación</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <h5 class="text-center">Se aprobará la solicitud de el estudiante <span style="font-weight: 500;font-size: 1.2rem;">{{solicitud.nombre}}</span></h5>
    </div>
    <div class="modal-footer justify-content-center">
      <button type="button" class="btn btn-lg btn-danger mr-4" data-dismiss="modal">Cerrar</button>
      <form action="{% url 'approve_solicitud' solicitud.pk TOKEN %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-lg btn-success ml-4" name="BtnSubmit" value="Aprobar"></input>
      </form>
    </div>
  </div>
</div>

<!-- TODO: REALIZAR VISTA MOVIL -->

src/practicas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- JQuery -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <!-- CSS CDN DE MDBOOTSTRAP -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/css/mdb.min.css" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous" />
        <link rel = "stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        {% block css %}{% endblock %}
        {% block Title %}{% endblock %}
    </head>

    <body style="background-color: rgb(235, 235, 235);">
        {% block Main %}{% endblock %}
    </body>


<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/js/mdb.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.20/datatables.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>
{% block js %}{% endblock %}

</html>

src/practicas/templates/delete_solicitud.html
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header grey lighten-2">
      <h4 class="modal-title w-100 text-center" id="myModalLabel" style="font-weight: 500;font-size: 1.5rem;">Advertencia</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <h5 class="text-center">¿Está seguro que desea eliminar su solicitud?</h5>
    </div>
    <div class="modal-footer justify-content-center">
      <button type="button" class="btn btn-default shadow-none btn-lg ml-5" data-dismiss="modal">Cerrar</button>
      <form action="{% url 'delete_solicitud' TOKEN %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn shadow-none mx-5 btn-danger btn-lg" name="BtnSubmit" value="Eliminar"></input>
      </form>
    </div>
  </div>
</div>

src/practicas/templates/error.html
<br />
<br />
<div class="card">
  <div class="card-body">
    <h2 class="text-center text-danger">
    NO POSEE LOS PERMISOS NECESARIOS PARA ACCEDER A ESTA VISTA.
    </h2>
  </div>
</div>

src/practicas/templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h5 align="center">{{ message }}</h5>
  </div>
{% endfor %}

src/practicas/templates/reject_solicitud.html
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header grey lighten-2">
      <h4 class="modal-title w-100 text-center" id="myModalLabel" style="font-weight: 500;font-size: 1.5rem;">Advertencia Rechazo</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body ">
      <h5 class="text-center">Se rechazará la solicitud de el estudiante <span style="font-weight: 500;font-size: 1.2rem;">{{solicitud.nombre}}</span></h5>
      <form action="{% url 'reject_solicitud' solicitud.pk TOKEN %}" method="post">
      <div class="row">
        <div class="col-2"></div>
        <div class="form-group col-9 col-sm-9 col-md-9 col-lg-9 col-xl-9 ml-n4_custom mt-n2">
          <label for="id_rejected_reason" class="col-form-label pl-2 pb-0">Ingrese motivo:</label>
          <textarea class="validate form-control form-control-lg" id="id_rejected_reason" name="rejected_reason" rows="3" required></textarea>
        </div>
    </div>
    <div class="modal-footer justify-content-center">
      <button type="button" class="btn btn-default shadow-none btn-lg" data-dismiss="modal">Cerrar</button>
        {% csrf_token %}
        <input type="submit" class="btn shadow-none mx-5 btn-danger btn-lg" name="BtnSubmit" value="Rechazar"></input>
      </form>
    </div>
  </div>
</div>

src/practicas/templates/solicitud_view.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        {% block Title %}
        <title>
            Prácticas EIT-UDP
        </title>
        {% endblock %}
    </head>

    <body>
        {% block Main %}
        <main>
          <div class="container">
            {% if error %}
            {% include 'error.html' %}
            {% else %}
            {% include 'messages.html' %}
            <div class="card mt-4">
              <div class="card-body">
                <h1 class="card-title">{{solicitud.nombre}}</h1>
                <h4 class="mt-n2"> {{solicitud.numero_practica}}</h4>
                <br/>
                <h4> Empresa: {{solicitud.nombre_empresa}}</h4>
                <h4> Inicio práctica: {{solicitud.inicio_practica}}</h4>
                <h4> Termino práctica: {{solicitud.termino_practica}}</h4>
                <h4> Estado de aprobación: </h4>
                <ul class="">
                  <li><h5>Coordinación de Prácticas de la EIT:
                    <span class="ml-2">
                      {% if solicitud.status_m %}
                      <i class="fas fa-check text-success fa-2x"></i>
                      {% else %}
                      <i class="fas fa-minus fa-lg"></i>
                  {% endif %}
                    </span>
                    </h5></li>
                  <li><h5>Coordinación de Vinculación Laboral:
                    <span class="ml-2">
                      {% if solicitud.status_v %}
                      <i class="fas fa-check text-success fa-2x"></i>
                      {% else %}
                      <i class="fas fa-minus fa-lg"></i>
                      {% endif %}
                    </span>
                  </h5></li>
                </ul>
                <br/>
                {% if solicitud.is_rejected %}
                <h3 style="color: red;"> Su solicitud fue rechazada por el siguiente motivo: {{solicitud.rejected_reason}} </h3>
                {% endif %}

                {% if solicitud.status_m == True and solicitud.status_v == True %}
                <h3 class="text-success"> Su solicitud de práctica fue aprobada. </h3>
                {% endif %}
                <br/>

                <button type="button" class="btn shadow-none btn-danger mr-3" onclick="return open_modal('{% url 'delete_solicitud' TOKEN %}')"> <span style="font-size: 1rem;">Eliminar</span> </button>
                {% if solicitud.is_rejected %}
                <a type="button" class="btn shadow-none btn-default" style="font-size: 1rem;" href="{% url 'solicitud_correction' TOKEN %}">Recorregir</a>

                {% else %}
                <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="Disponible en caso de ser rechazada la solicitud." >
                  <button type="button" class="btn shadow-none btn-default" style="font-size: 1rem;" disabled>Recorregir</button>
                </span>
                {% endif %}

              </div>

            </div>
            {% endif %}
          </div>
        </main>
        <div id="popup" class="modal" role="dialog"></div>
        {% endblock %}
    </body>
</html>

{% block js %}
<script type="text/javascript" src="{% static "js/tooltip.js" %}"></script>
<script type="text/javascript" src="{% static "js/modal.js" %}"></script>
{% endblock %}

src/practicas/templates/solicitudes.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% block Title %}
<title>
    UDP - Solicitudes
</title>
{% endblock %}
{% block css %}
<link rel = "stylesheet" type="text/css" href="{% static 'css/datatable.css' %}">
{% endblock %}
{% block Main %}
<main>
    <div class="container-fluid">
        {% if error %}
        {% include 'error.html' %}
        {% else %}
        {% include 'messages.html' %}
        <table id="dataTable">
            <thead class="thead_solicitudes">
                <tr>
                    <th scope="col" class="text-center">Rut</th>
                    <th scope="col" class="text-center">Nombre</th>
                    <th scope="col" class="text-center">Empresa</th>
                    <th scope="col" class="text-center">N° Práctica</th>
                    <th scope="col" class="text-center"></th>
                </tr>
            </thead>

            {% for solicitud in solicitudes %}
                <tr class="text-center">
                    <td class="tablaFont" style="width: 15%"> {{ solicitud.rut }} </td>
                    <td class="tablaFont" style="width: 30%"> {{ solicitud.nombre }} </td>
                    <td class="tablaFont" style="width: 20%"> {{ solicitud.nombre_empresa }} </td>
                    <td class="tablaFont" style="width: 15%"> {{ solicitud.numero_practica}} </td>
                    <td style="width: 20%">
                        <div class="btn-group">
                            <button class="btn nohover transparentBG z-depth-0 black-text" data-placement="top" onclick="return open_modal('{% url 'solicitud_details' solicitud.pk TOKEN %}')" title="Más información"><i class="fas fa-info fa-2x"></i></button>
                            <button class="btn nohover transparentBG z-depth-0 green-text" onclick="return open_modal('{% url 'approve_solicitud' solicitud.pk TOKEN %}')" data-placement="top" title="Aprobar"><i class="fas fa-check fa-2x"></i></button>
                            <button class="btn nohover transparentBG z-depth-0 red-text" onclick="return open_modal('{% url 'reject_solicitud' solicitud.pk TOKEN %}')" data-placement="top" title="Rechazar"><i class="fas fa-times fa-2x"></i></button>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</main>
<div id="popup" class="modal" role="dialog"></div>
{% endblock %}
</html>

{% block js %}
<script type="text/javascript" src="{% static "js/modal.js" %}"></script>
<script type="text/javascript" src="{% static "js/datatable.js" %}"></script>
{% endblock %}